### ISSUE TITLE
Add setsockopt method to the 'Socket' interface

### ISSUE THREAD

**Issue by qpmr** [rust-netlink/netlink-sys#18]
Hi, I am using a crate that depends on yours (thanks for the implementation, by the way :) ) and I need to set some socket options (for example, SO_RCVBUF). The current Socket interface doesn't provide an access to this method and you use it internally only (why?). Maybe I can add it to the Socket interface?
```
impl Socket {
    ...
    pub fn bind(&mut self, addr: &SocketAddr) -> Result<()> {
    ...
    }
    ...
    pub fn connect(&self, remote_addr: &SocketAddr) -> Result<()> {
    ...
    }
    ...
    pub fn setsockopt<T>(
        fd: RawFd,
        level: libc::c_int,
        option: libc::c_int,
        payload: T,
    ) -> Result<()> {
        let payload = &payload as *const T as *const libc::c_void;
        let payload_len = mem::size_of::<T>() as libc::socklen_t;
    
        let res =
            unsafe { libc::setsockopt(fd, level, option, payload, payload_len) };
        if res < 0 {
            return Err(Error::last_os_error());
        }
        Ok(())
    }
}
```

**Comment by cathay4t** [comment]
I am currently using stuff like:

```rust
    let (mut connection, handle, _) = new_connection()?;
    if unsafe {
        libc::setsockopt(
            connection.socket_mut().as_raw_fd(),
            libc::SOL_NETLINK,
            NETLINK_GET_STRICT_CHK,
            1u32.to_ne_bytes().as_ptr() as *const _,
            4,
        )
    } != 0
    {
        let e = NisporError::bug(format!(
            "Failed to set socket option NETLINK_GET_STRICT_CHK: error {}",
            std::io::Error::last_os_error()
        ));
        return Err(e);
    }

    tokio::spawn(connection);
```

PR will be welcome for wrapping above into API would be great!.

Meanwhile, `nix::sys::ioctl` might be better than `libc::ioctl`.

**Comment by qpmr** [comment]
Sure, I will create a PR later in a few days

**Comment by qpmr** [comment]
@cathay4t Hi, I decided do not expose the setsockopt(), but only option that I tested (get/set SO_RCVBUF). And it is also save backward compatibility with existed projects.

**Comment by qpmr** [comment]
@cathay4t  Hi again, maybe you have some plans about the next release? : ) 
Some other issue waiting for these tiny changes [Listener for the exiting tasks](https://github.com/kawamuray/linux-taskstats-rs/issues/10)
And in my project I use this linux-taskstats-rs crate. This changes are optional (useful for some corner cases), but I have added them to be compliant with the documentation [taskstats](https://www.kernel.org/doc/Documentation/accounting/taskstats.txt)

**Comment by cathay4t** [comment]
Are you expecting me to do new release to include PR #20 ?

**Comment by qpmr** [comment]
Sorry for misleading: at the first place I wanted exposing `setsockopt()` BUT then I realized, that it is not a good idea. So I created this #20 PR . I am not going to create other PR at this crate ) I just want to create other PR in the [linux-taskstats-rs](https://github.com/kawamuray/linux-taskstats-rs/issues/10) crate which is use your crate

**Comment by cathay4t** [comment]
The new 0.8.6 release uploaded to crates.io. `cargo update` could do the magic on refresh your local cache.

**Comment by qpmr** [comment]
Thank's!
